config/routes.rb
FoursquareSpeed::Application.routes.draw do
  
  resource :session do
    collection do
      get 'callback'
    end
  end
  
  resources :examples do
    collection do
      get 'user'
      get 'checkins'
      get 'friends'
      get 'venues_search'
      get 'venue_details'
    end
  end

  resources :api do
    collection do
      get 'checkins'
      get 'user'
      get 'pull_4sq'
      get 'pull_4sq_all'
      get 'geojson'
      get 'geojson_all'
    end
  end
  

  root :to => "sessions#new"

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  Usernames = %w(rubinovitz seagaia2 chimeracoder zencephalon linstantnoodles chmullig
  thetabyte t3hprogrammer basilksiddiqui borowskidaniel drjid sclarawu jbcima a2 djj2115
  dskang celehner exchgr kyle_petrovich jmatth92 katieposkaitis elbuo8 jfriedhoff dotgil
  hackny ) #sanapants

  def self.twitter_client
    @twitter_client ||= Twitter::Client.new(consumer_key: Settings.twitter_consumer_key, consumer_secret: Settings.twitter_consumer_secret, oauth_token: Settings.twitter_access_key, oauth_token_secret: Settings.twitter_access_secret)
  end

  def get_timeline(user)
    @twitter_client.user_timeline(user, count: 200)
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :checkins

  def fsq_user 
    @fsq_user ||= Foursquare::Base.new(token).users.find("self")
  end

  def self.user_from_token(access_token)
    User.find_or_create_by_token(access_token)
  end

  def self.user_from_current_user
    User.find_or_create_by_token(current_user.access_token)
  end

  def name
    @name ||= fsq_user.name
  end

  def pull_checkins
    count = 250
    offset = 0
    last_pulled = checkins.order(:checkedin_at).last.try(:checkedin_at) || '1370059200'

    while count == 250
      newcheckins = fsq_user.checkins(limit: count, offset: offset, afterTimestamp: last_pulled )
      newcheckins.each do |c|
        Checkin.find_or_create_by_checkin_id(user_id: id, checkin_id: c.id, checkedin_at: c.json['createdAt'], blob: c.json.to_json)
      end
      count = newcheckins.count
      offset += count
    end
    offset
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  
  before_filter :require_user
  
  def index
    # list all the examples
    
  end

  def show
  end

  respond_to :json, :html, :xml
  def pull_4sq
    num = 0
    num = User.user_from_token(session['access_token']).pull_checkins
    render json: num
  end

  respond_to :json, :html, :xml
  def pull_4sq_all
    added = {}
    User.where("token != ''").all.each do |u|
      added[u.id] = u.pull_checkins
    end
    
    render json: added
  end
  
  respond_to :json, :xml, :html
  def checkins
    u = User.user_from_token(session['access_token'])
    u.pull_checkins

    render json: u.checkins.map{|c| ActiveSupport::JSON.decode(c.blob)  }
  end

  respond_to :json, :xml, :html
  def geojson
    u = User.user_from_token(session['access_token'])
    checkins = []
    u.checkins.map{|c| ActiveSupport::JSON.decode(c.blob)}.each do |c|
      checkins << {
        'type' => 'Feature',
        'geometry' => {
          'type' => 'Point',
          'coordinates' => [c['venue']['location']['lng'], c['venue']['location']['lat']]
        },
        'properties' => {
          'name' => "#{u.name} at #{c['venue']['name']}",
          'id' => c['id'],
          'timestamp' => c['createdAt'],
          'datetime' => Time.strptime(c['createdAt'].to_s, '%s').to_datetime,
          'user' => u.name,
          'text' => c['shout'] || '',
          'photos' => c['photos']['items'],
          'likes' => c['likes']['count']
         }
      }
    end
    render json: {'type' => 'FeatureCollection', 'features' => checkins}
  end

  respond_to :json, :xml, :html
  def geojson_all
    checkins = []
    User.where("token != ''").each do |u|
      u.checkins.map{|c| ActiveSupport::JSON.decode(c.blob)}.each do |c|
        next if c.has_key? 'private'
        checkins << {
          'type' => 'Feature',
          'geometry' => {
            'type' => 'Point',
            'coordinates' => [c['venue']['location']['lng'], c['venue']['location']['lat']]
          },
          'properties' => {
            'name' => "#{u.name} at #{c['venue']['name']}",
            'id' => c['id'],
            'timestamp' => c['createdAt'],
            'datetime' => Time.strptime(c['createdAt'].to_s, '%s').to_datetime,
            'venue' => c['venue']['name'],
            'user' => u.name,
            'text' => c['shout'] || '',
            'photo' => c['photos'].try(:[], 'items').try(:first).try(:[], 'url') || '',
            'likes' => c['likes']['count'] + c['comments']['count']
           }
        }
      end
    end

    render json: {'type' => 'FeatureCollection', 'features' => checkins}
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
    def require_user
      unless current_user
        redirect_to root_path
      end
    end
  
    def current_user
      return nil if session[:access_token].blank?
      begin
        foursquare = Foursquare::Base.new(session[:access_token])
        @current_user ||= foursquare.users.find("self")
      rescue Foursquare::InvalidAuth
        nil
      end
    end
    
    def foursquare
      unless current_user
        @foursquare ||= Foursquare::Base.new(Settings.app_id, Settings.app_secret)
      else
        @foursquare ||= Foursquare::Base.new(session[:access_token])
      end
    end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  
  before_filter :require_user
  
  def index
    # list all the examples
    
  end
  
  def user
  end
 
  respond_to :json, :xml, :html
  def checkins
    respond_with(current_user) 
  end
  
  def friends
  end
  
  def venues_search
    if params[:name]
      # venues is a hash, with keys that represents different type of results
      # see "Response Fields" in this page: https://developer.foursquare.com/docs/venues/search.html
      # for more details
      @venues = foursquare.venues.search(:query => params[:name], :ll => "48.857,2.349")
    end
  end
  
  def venue_details
    # default venue is the "Tour Eiffel"
    @venue_id = params[:venue_id] || "185194"
    @venue = foursquare.venues.find(@venue_id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    user = User.find_or_create_by_token(@access_token)
    user.token = @access_token
    user.save!

    return redirect_to examples_path if current_user
    @authorize_url = foursquare.authorize_url(callback_session_url)
  end
  
  def callback
    code = params[:code]
    @access_token = foursquare.access_token(code, callback_session_url)
    session[:access_token] = @access_token

    Rails.logger.debug @access_token

    user = User.find_or_create_by_token(@access_token)
    user.token = @access_token
    user.name = user.fsq_user.name
    user.save!

    redirect_to examples_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def sitemap(text)
    "<h2>#{link_to('Examples', examples_path)} > #{text}</h2>".html_safe
  end
  
  def see_more(link)
    "<h4>#{link_to("See More at Foursquare Documentation", link)}</h4>".html_safe
  end
  
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/examples/checkins.html.haml
= sitemap "#{current_user.name}'s Recent Checkins"

= see_more("https://developer.foursquare.com/docs/explore.html#req=users/self/checkins")

- current_user.checkins(afterTimestamp: 1370059200, limit: 250).each do |checkin|
  .checkin
    .venue
      .icon
        = image_tag(checkin.venue.icon) if checkin.venue
      .content
        .name= "@ #{checkin.venue.name}" if checkin.venue
        .shout= checkin.shout
        .time= time_ago_in_words(checkin.created_at)
      /= checkin.inspect

app/views/examples/friends.html.haml
= sitemap "#{current_user.name}'s friends"

= see_more("https://developer.foursquare.com/docs/explore.html#req=users/self/friends")

- current_user.friends.each do |friend|
  .friend
    .photo
      = image_tag(friend.photo) if friend.photo
    .info
      .name= "#{friend.first_name} #{friend.last_name}"
      .city= friend.home_city
      /= friend.inspect

app/views/examples/index.html.haml
%h2 Please load your hackNY checkins!
%ul
  %li= link_to "Refresh your 4sq checkin cache", pull_4sq_api_index_path
  %li= link_to "Dump your checkins", checkins_api_index_path



Boring shit that comes for free
%ul
  %li= link_to "Information about Current User", user_examples_path
  %li= link_to "List of Friends of Current User", friends_examples_path
  %li= link_to "List of Checkins from Current User", checkins_examples_path
  %li= link_to "Search for Venues", venues_search_examples_path
  %li= link_to "Get Details about a specific Venue", venue_details_examples_path

app/views/examples/user.html.haml
= sitemap("#{current_user.name} Profile")

= see_more "https://developer.foursquare.com/docs/explore.html#req=users/self"

%table
  %tr
    %td First Name
    %td= current_user.first_name
  %tr
    %td Last Name
    %td= current_user.last_name 
  %tr
    %td Photo
    %td= image_tag current_user.photo
  %tr
    %td Email
    %td= current_user.email
    
  %tr
    %td More
    %td= link_to "See documentation", "https://developer.foursquare.com/docs/explore.html#req=users/self"

app/views/examples/venue_details.html.haml
= sitemap "#{@venue.name}"

= see_more "https://developer.foursquare.com/docs/explore.html#req=venues/#{@venue_id}"

%table
  %tr
    %td Name
    %td= @venue.name
  %tr
    %td Location
    %td= @venue.location.address
  - if @venue.primary_category
    %tr
      %td Primary Category
      %td= @venue.primary_category.name
  %tr
    %td Categories
    %td
      - @venue.categories.each do |category|
        %ul
          %li
            = image_tag category["icon"]
            = category["name"]
  %tr
    %td Checkins Count
    %td= @venue.stats["checkinsCount"]
    
  %tr
    %td Photos
    %td
      %p
        = @venue.photos_count
        photos
        - unless @venue.photos.blank?
          <br />
          All photos may not be present here, use "all_photos" method to get more photos
          <br />
          Note that various size are available for each photo (original, 300x300, 100x100, 36x36)
      - @venue.photos.each do |photo|
        = link_to image_tag(photo.square_100_url), photo.url
    
  %tr
    %td More
    %td= link_to "See documentation", "https://developer.foursquare.com/docs/explore.html#req=venues/#{@venue_id}"

app/views/examples/venues_search.html.haml
= sitemap "Search for Venues"

%p Search for venues in Paris. For example: 
= link_to "Tour Eiffel", :name => "Tour Eiffel"
= link_to "Louvre", :name => "Louvre"
= link_to "Montmartre", :name => "Montmartre"
%p= see_more "https://developer.foursquare.com/docs/venues/search.html"
  
- form_tag nil, :method => :get do
  = label_tag "Venue Name:"
  = text_field_tag "name", params[:name]
  near Paris
  = submit_tag "search"
  
- if @venues
  
  #results
    - @venues["places"].each do |venue|
      .venue
        .icon= image_tag venue.icon
        .content
          .name= link_to venue.name, venue_details_examples_path(:venue_id => venue.id)

app/views/layouts/application.html.haml
!!! XHTML
%html
  %head
    %title Foursquare API
    = stylesheet_link_tag 'html'
  %body
    :plain
      <a href="http://github.com/pierrevalade/foursquare-rails-examples"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://d3nwyuy0nl342s.cloudfront.net/img/7afbc8b248c68eb468279e8c17986ad46549fb71/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub"></a>
    
    #page
      #rails
        = image_tag 'rails.png', :height => "30"
      #foursquare
        = image_tag 'poweredbyfoursquare-icon.png'
      %h1#title
        = link_to "Foursquare + Rails", root_path
        
      = yield
    
      #devs
        made by
        %ul
          %li= link_to "Chris Mulligan", "http://twitter.com/chmullig"
          %li= link_to "Dan Mundy", "http://twitter.com/exchgr"
          %li= link_to "For hackNY", "http://hackny.org"
          %li= link_to "Based on Pierre and friend's Foursquare Rails Example", "https://github.com/pierrevalade/foursquare-rails-examples"